#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc monitor -d 1 2 3 4 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## Dual Screen
if [[ $( xrandr -q | grep 'HDMI-0 connected' )  ]]; then
	bash ~/display.sh
	bspc monitor eDP-1-1 -d 1 2 3 4 5
	bspc monitor HDMI-0 -d 1 2 3 4 5
	polybar -q sec -c ~/.config/polybar/colorblocks/config2.ini &
	polybar -q main -c ~/.config/polybar/colorblocks/config.ini &
else
	bash ~/display_s.sh
	bspc monitor -g 1920x1080+0+0
	bspc monitor -d 1 2 3 4 5
	bash ~/.config/polybar/launch.sh --colorblocks
fi

## Workspaces

## Polybar

## Wallpaper
xwallpaper --zoom ~/walls/one.jpg
